database:
  type: "postgres" # "mysql" or "postgres"
  server_id: 1 #for mysql only
sync:
  enabled: true
  sync_request:
    max_retries: 3 # max retries on sync failure (e.g connection issues/error)
    retry_delay: "3s" # time to wait between retry
    request_timeout: "1s" # excuetion time for each sync request
  batch:
    batch_size: 4 # batch size before offloading 
    flush_duration: "5s" #time in milliseconds to wait before offloading batch  
  events:
    event_types:
      - "insert"
      - "update"
      - "delete"
  mappings:
    - database_table: "users" #defaults to public schema, for mysql("default.users")= db[default] table[users]
      meilisearch_index: "users"
      meilisearch_index_document_uid: "id"
      fields:
        - id: ""
        - name: ""
        - email: ""
    - database_table: "products"
      meilisearch_index: "products"
      meilisearch_index_document_uid: "id"
      fields:
        - "*"
