database:
  type: "postgres" # "mysql" or "postgres"
sync:
  enabled: true
  #connection:
  #   max_retries: 3
  #   retry_backoff: 2000 # time to wait between retry
  #batch:
  #  batch_size: 50 # batch size before offloading (to be implemented)
  # flush: 2000 #time in seconds to wait before offloading batch (to be implemented) 
  events:
    event_types:
      - "insert"
      - "update"
      - "delete"
  mappings:
    - database_table: "users"
      meilisearch_index: "users"
      meilisearch_index_document_uid: "id"
      fields:
        - "id"
        - "name"
        - "email"
    - database_table: "products"
      meilisearch_index: "products"
      meilisearch_index_document_uid: "id"
      fields:
        - "*"
